// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeopleIO.Infrastructure.Context;

#nullable disable

namespace PeopleIO.Infrastructure.Migrations
{
    [DbContext(typeof(PeopleIoContext))]
    [Migration("20251128031909_UpdateColaboradorModel")]
    partial class UpdateColaboradorModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PeopleIO.Domain.Entity.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CNHDataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CNHNumero")
                        .HasColumnType("text");

                    b.Property<string>("CNHOrgaoEmissor")
                        .HasColumnType("text");

                    b.Property<string>("CNHTipo")
                        .HasColumnType("text");

                    b.Property<string>("CNHUF")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CTPSDataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CTPSNumero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CTPSSerie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CTPSUF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("CorRaca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Escolaridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IdentidadeDataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentidadeNumero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentidadeOrgaoEmissor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentidadeUF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloEleitorNumero")
                        .HasColumnType("text");

                    b.Property<string>("TituloSecao")
                        .HasColumnType("text");

                    b.Property<string>("TituloUF")
                        .HasColumnType("text");

                    b.Property<string>("TituloZona")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("colaborador", (string)null);
                });

            modelBuilder.Entity("PeopleIO.Domain.Entity.Colaborador", b =>
                {
                    b.OwnsOne("PeopleIO.Domain.Entity.Documento", "ArquivoCNH", b1 =>
                        {
                            b1.Property<Guid>("ColaboradorId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DataUpload")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ArquivoCNHDataUpload");

                            b1.Property<string>("NomeArquivo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoCNHNome");

                            b1.Property<string>("TipoMime")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoCNHTipoMime");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoCNHURL");

                            b1.HasKey("ColaboradorId");

                            b1.ToTable("colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorId");
                        });

                    b.OwnsOne("PeopleIO.Domain.Entity.Documento", "ArquivoCPF", b1 =>
                        {
                            b1.Property<Guid>("ColaboradorId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DataUpload")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ArquivoCPFDataUpload");

                            b1.Property<string>("NomeArquivo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoCPFNome");

                            b1.Property<string>("TipoMime")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoCPFTipoMime");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoCPFURL");

                            b1.HasKey("ColaboradorId");

                            b1.ToTable("colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorId");
                        });

                    b.OwnsOne("PeopleIO.Domain.Entity.Documento", "ArquivoComprovanteResidencia", b1 =>
                        {
                            b1.Property<Guid>("ColaboradorId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DataUpload")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ArquivoResidenciaDataUpload");

                            b1.Property<string>("NomeArquivo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoResidenciaNome");

                            b1.Property<string>("TipoMime")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoResidenciaTipoMime");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoResidenciaURL");

                            b1.HasKey("ColaboradorId");

                            b1.ToTable("colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorId");
                        });

                    b.OwnsOne("PeopleIO.Domain.Entity.Documento", "ArquivoRG", b1 =>
                        {
                            b1.Property<Guid>("ColaboradorId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DataUpload")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ArquivoRGDataUpload");

                            b1.Property<string>("NomeArquivo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoRGNome");

                            b1.Property<string>("TipoMime")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoRGTipoMime");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ArquivoRGURL");

                            b1.HasKey("ColaboradorId");

                            b1.ToTable("colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorId");
                        });

                    b.OwnsOne("PeopleIO.Domain.Entity.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ColaboradorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Bairro");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Estado");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Numero");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Rua");

                            b1.HasKey("ColaboradorId");

                            b1.ToTable("colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorId");
                        });

                    b.Navigation("ArquivoCNH");

                    b.Navigation("ArquivoCPF");

                    b.Navigation("ArquivoComprovanteResidencia");

                    b.Navigation("ArquivoRG");

                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
