namespace PeopleIO.Communication;

public record CreateColaboradorRequest(
    string Nome,
    string CPF,
    DateTime DataNascimento,
    string Email,
    string Telefone,
    EnderecoRequest Endereco,
    string Cargo,
    string Departamento,
    DateTime DataAdmissao,
    string IdentidadeNumero,
    string IdentidadeOrgaoEmissor,
    string IdentidadeUF,
    DateTime IdentidadeDataEmissao,
    string CTPSNumero,
    string CTPSSerie,
    DateTime CTPSDataEmissao,
    string CTPSUF,
    string TituloEleitor,
    DateTime TituloDataEmissao,
    string TituloUF,
    string TituloZona,
    string TituloSecao,
    string CNHNumero,
    string CNHUF,
    DateTime CNHDataVencimento,
    string CNHOrgaoEmissor,
    string CNHTipo,
    string CorRaca,
    string Sexo,
    string Escolaridade,
    string EstadoCivil,
    string Naturalidade,
    string Nacionalidade
);